people = [
  {
    name: 'Nathan McNeese',
    title: 'director',
    program: 'Human Centered Computing',
    researchInterests: ['Human Factors','Human Computer Interaction','Artificial Intelligence','Computer Supported Cooperative Work','Information Sciences',],
    description: 'I am an Assistant Professor and Director of the Team Research Analytics in Computational Environments (TRACE) Research Group within the division of Human-Centered Computing in the School of Computing at Clemson University. I also hold an affiliation in Clemson’s Human Factors Institute. In addition, I am a Faculty Scholar in Clemson’s School of Health Research and a Watt Family Faculty Fellow. I received my PhD in Information Sciences & Technology with a focus on Team Decision Making, Cognition, and Computer Supported Collaborative Work from The Pennsylvania State University in the fall of 2014. After graduation, I accepted a position to be a Postdoctoral Scholar and Research Associate in Human Systems Engineering at Arizona State University working directly with Dr. Nancy Cooke.',
    personalWebsiteUrl: 'https://nathanmcneese.weebly.com/',
    linkedInUrl: 'https://www.linkedin.com/in/nathanmcneese',
    googleScholarUrl: 'https://scholar-google-com.libproxy.clemson.edu/citations?user=G1CnZ38AAAAJ&hl=en&oi=sra',
    twitterUrl: 'https://twitter.com/nathanmcneese',
    cvUrl: 'https://nathanmcneese.weebly.com/cv.html',
  },
  {
    name: 'Christopher Flathmann',
    title: 'PhD Student, Alumni',
    program: 'Human Centered Computing',
    img_cat: 'alumni',
    img_url: 'christopher-flathmann-Portrait.jpg',
    researchInterests: ['Swarm Intelligence','Responsible AI','Modular Human-Agent Teams','Ethics in Artificial Intelligence',],
    description:'Ahoy there, I’m Chris Flathmann and I’m a PhD student studying Human Centered Computing at Clemson University as a Research Assistant in the TRACE Research Group.  After earning a BS in Computer Science from Clemson University, completing internships at Amazon and Michelin, and working as an undergraduate research assistant at Clemson, I decided that I wanted to pursue a PhD to futher explore and develop my interests in computing.  Since entering the Human Centered Computing program and the TRACE Research Group I have also developed a large interest in the human side of computing and the interaction between humans and the rapidly developing technology that is Artificial Intelligence.  Aside from my research work I also have personal interests and hobbies like disc golf, video/tabletop games, movies (mainly sci-fi and Rom-Com), and mechanical keyboards.',
    personalWebsiteUrl: 'https://chrisflathmann.com',
    linkedInUrl: 'https://www.linkedin.com/in/christopher-flathmann/',
    googleScholarUrl:'https://scholar.google.com/citations?user=b2dlWbwAAAAJ&hl=en&oi=ao',
    gitHubUrl: 'https://github.com/cflathm',
    cvUrl: 'UNDER PDF SECTION',
  },
  {
    name: 'Beau Schelble',
    title: 'PhD Student, Alumni',
    program: 'Human Centered Computing',
    img_cat: 'alumni',
    img_url: 'beau-schelble-Portrait.jpg',
    researchInterests: ['Team Cognition in Human-Autonomy Teams','Multi-Agent Systems','Human-AI Teams in Industry 4.0 Applications',],
    description:'Howdy! My name is Beau Schelble and I was born and raised in Chapin, South Carolina. I am a life long Clemson fan with parents who also graduated from Clemson University so Clemson sports are a big pastime of mine. I also graduated from Clemson University with an undergraduate degree in Psychology in December 2018 and began pursuing a PhD in Human-Centered Computing in the Fall of 2019. I grew up with a love of people and technology so naturally I gravitated towards research that incorporated both topics and have loved learning and becoming more hands on with computing in our lab.',
    linkedInUrl: 'https://www.linkedin.com/in/beau-schelble-498675135',
    gitHubUrl: 'https://github.com/bschelb',
  },
  {
    name: 'Rui Zhang',
    title: 'PhD Student, Alumni',
    program: 'Human Centered Computing',
    img_cat: 'alumni',
    img_url: 'rui-Zhang-Portrait.jpg',
    researchInterests: ['Human-Machine team','Team Decision Making','Human-Computer Interaction',],
    description:'I am a PhD student in the Human-Centered Computing Division of the School of Computing at Clemson University. I received her M.S. and B.S. in Aerospace Engineering from Beijing Institute of Technology (China).',
    personalWebsiteUrl: 'https://helloimrui.com/',
    linkedInUrl: 'https://www.linkedin.com/in/rui-zhang-5b6607172/',
    gitHubUrl: 'https://github.com/Rui365',
    resumeUrl: 'https://helloimrui.com/assets/resume-rui-zhang.pdf',
  },
  {
    name: 'Geoff Musick',
    title: 'PhD Student, Alumni',
    program: 'Human Centered Computing',
    img_cat: 'alumni',
    img_url: 'geoff-Musick-Portrait.jpg',
    researchInterests: ['Human Autonomy Interaction', 'Human Autonomy Teaming'],
    description: 'My name is Geoff Musick and I’m from Nashville, TN. My bachelor’s degree was in Biochemistry with minors in Biology and Math. Before moving to Clemson, I spent 3 years teaching Physics and AP Biology. While teaching I received a masters degree in education.  Additionally I spent a couple years making educational video game apps for high school physics students. I started working on my PhD in Human-Centered Computing in the Spring of 2019.',
    linkedInUrl: 'https://www.linkedin.com/in/geoff-musick/',
    gitHubUrl: 'https://github.com/musickgm',
  },
  {
    name: 'Nirali Bandaru',
    title: 'Masters Student, Alumni',
    program: 'Computer Engineering',
    img_cat: 'alumni',
    researchInterests: ['Reinforcement Learning','Expert Systems','Neural Networks'],
    description:'Hello! My name is Nirali Bandaru, and I’ve had an interesting exposure to different cultures growing up. I was born in India and my family migrated to the US when I was 10. Being an only child, I developed various hobbies such as painting, writing, and singing. I went back to India for college and majored in Electronics and Communications Engineering at VIT University. I’m now pursuing a Master’s in Computer Engineering at Clemson with a focus on Intelligent Systems. I have a special interest in Artificial Intelligence and I’m currently conducting research in how AI could help enhance and maximize productivity in project teams.',
    linkedInUrl: 'https://www.linkedin.com/in/niralibandaru/',
  },
  {
    name: 'Bekk Blando',
    title: 'Undergraduate Student, Alumni',
    program: 'Mathematical Sciences',
    img_cat: 'alumni',
    description: 'I currently focus on biometrics, massive computational experiments, mathematics, and programming educational models, researching at both Clemson and Stanford. Improving education is extremely important and personal to me having started a non-profit dedicated to STEAM education, and organizing a programming bootcamp for students at Clemson. I am primarily motivated by societal payoff and the projects I choose to work on reflect this.',
    personalWebsiteUrl: 'http://bekkblando.com/',
    linkedInUrl: 'https://www.linkedin.com/in/bekk-blando-a3b97aa9',
    gitHubUrl: 'https://github.com/bekkblando',
    twitterUrl: 'https://twitter.com/bekkblando',
    resumeUrl: 'http://bekkblando.com/resume.html',
  },
  {
    name: 'Mark Blasko',
    img_cat: 'alumni',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    description: 'I am an undergraduate Computer Science major and Math minor.  I became interested in CS when I began casually exploring programming in high school.  My primary academic interests are data science, bioengineering, and algorithms.  I love exploring topics that involve a lot of both math and CS, and have more recently become interested in bioengineering.  Outside of academics, I enjoy watching football amongst other sports, and really enjoy exercise.',
    linkedInUrl: 'https://www.linkedin.com/in/mark-blasko-49a6b340',
  },
  {
    name: 'Rafael Dejesus',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'I’m Rafael DeJesus, a Computer Science undergraduate student minoring in Cyber Security. I enjoy problem solving and I see computer science as just a platform for that.  I have an interest in a lot of thing including technology, strategy, algorithms, government, teamwork, physics, philosophy, video games, design and electronics',
    personalWebsiteUrl: 'https://rafael09ed.github.io/',
    linkedInUrl: 'https://www.linkedin.com/in/rafael-dejesus-707000bb',
    gitHubUrl: 'https://github.com/Rafael09ED',
    twitterUrl: 'https://twitter.com/rafael09ed_',
  },
  {
    name: 'Casey Hird',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'My name is Casey Hird, I am from Spartanburg, SC and am currently a sophomore at Clemson University. I am majoring in computer engineering with minors in Computer Science and Mathematics. My research interests include bioelectrical systems, network security, and quantum mechanics.',
    linkedInUrl: 'https://www.linkedin.com/in/casey-hird-a07092161',
    twitterUrl: 'https://twitter.com/caseyhird',
  },
  {
    name: 'John Paul Lineberger',
    title: 'Undergraduate Student, Alumni',
    program: 'BioEngineering',
    img_cat: 'alumni',
    description: 'Howdy, my name is John Paul Lineberger and I’m from Greenville, SC. I am currently a senior undergraduate Bioengineer who recently joined the research lab. Prior to joining, I have had experience in machine learning applications, computer vision, creating end-to-end solutions, and medical imaging. When I’m not creating PyTorch models, you can find me taking photos, participating in automotive events, playing guitar, and racing home built drones.',
    linkedInUrl: 'https://www.linkedin.com/in/john-lineberger-892612152/',
    gitHubUrl: 'https://github.com/jplineb',
  },
  {
    name: 'Qwelian Tanner',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'How you doing, my name is Qwelian Tanner. I am a computer science undergrad student, and co-founder of lmbk(link). I enjoy lazing with my girlfriend Damali, reading, manga included, thoughtful discussion, walking my dog Nala, and philosophy. In this new era of information, the issues we face will be more representative of our failures to advance people and the institutions we inhabit, rather than our technological capabilities. My research interest are in data engineering, AI, and biometrics. My goal is to allow the complex self, and the interactions embodied in waking life, to persist in a manner that disarms methods of conflict.',
    personalWebsiteUrl: 'https://qwelian.com/',
    linkedInUrl: 'https://www.linkedin.com/in/qdt/',
    gitHubUrl: 'https://github.com/qweliant',
  },
  {
    name: 'Steve Russell',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: "Hey, I’m Stephen Russell, and I’m a junior in Computer Science. In my free time I like making music, building web applications, and learning factoids about random subjects that I’ll never remember. I’m working on projects related to Collective Intelligence, Human-AI Interaction, and Collaboration Tools, and I’m grateful to be involved in TRACE's research efforts answering some of the most interesting questions related to Human-Centered Computing.",
    personalWebsiteUrl: 'https://steve.works/',
    linkedInUrl: 'https://www.linkedin.com/in/stephen-russell-bb9187176/',
    gitHubUrl: 'https://github.com/stphnrssll',
  },
  {
    name: 'Aru Bhoop',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    description: 'Hi, my name is Aru. I’m an undergraduate computer science major from Indian Land, SC, currently performing research in the area of swarm Intelligence. I’m fascinated by the formation of groups in nature and wish to replicate that phenomenon in the context of artificial intelligence, which I believe is the key to solving some of the most challenging issues in machine learning today. Apart from researching, I like to spend my free time playing soccer, travelling, playing piano, or just kicking back and reading a good book.',
    personalWebsiteUrl: 'http://www.aru.ai/',
    linkedInUrl: 'http://www.linkedin.com/in/arubhoop',
    gitHubUrl: 'https://github.com/aru-py',
  },
  {
    name: 'Mari Kilgus',
    title: 'alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    researchInterests: ['Human AI Teaming', 'Happiness and Values'],
    description: 'Hi, my name is Mari Kilgus. I’m originally from Winston-Salem, NC but I currently live in Charlotte, NC. I’m a sophomore computer science and psychology double major. Computer science and psychology seems the ideal background to eventually work in the field of human computer interaction. I want to be able to design products with people’s capabilities and limitations in mind. I enjoy applying skills which is why I also love playing flute. I had a great time in Tiger Band supporting the football team at all of the games and I’m looking forward to the rest of my time at Clemson.',
  },
  {
    name: 'Sarah Morrison',
    title: 'Undergraduate Student, Alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    description: 'Hey, my name is Sarah Morrison and I am from Somers, New York. I am a senior computer science major with a minor in Spanish and plan to graduate in May 2020. I hope to work in New York City after graduation as a project manager for a technology company. I love to travel the world and go on lots of hikes.',
    linkedInUrl: 'http://www.linkedin.com/in/sarahrosemorrison',
  },
  {
    name: 'Jack Carroll',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    researchInterests: ['artificial intelligence', 'theoretical computer science', 'and human-centered computing'],
    description: 'Hi, my name is Jack Carroll and I am originally from Portland, Maine. I am a computer science major with a minor in economics. Some of my hobbies include frisbee, rock climbing, and basically anything else outdoors.',
    personalWebsiteUrl: 'https://jpcarroll.dev/',
    linkedInUrl: 'https://www.linkedin.com/in/jp-carroll/',
    googleScholarUrl: 'https://scholar.google.com/citations?user=QVV2LEEAAAAJ',
    gitHubUrl: 'https://github.com/jpcarroll',
    resumeUrl: '',
  },
  {
    name: 'Dylan Cathapermal',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'Hi! My name is Dylan Cathapermal and I’m from Sterling Virginia. Though I am a long way from home, I’m so glad I came to Clemson. From the competitive football culture, to the ambition of the TRACE Lab, Clemson embodies so many characteristics that I not only have but want to improve. I am an undergraduate student majoring in Computer Science with a minor in mathematical sciences, as well as an incoming Summer 2020 intern at Amazon Web Services in Crystal City, Virginia. From a young age I have always had a passion for technology and innovation and I love being able to express that as part of the lab. I currently work with databases and web development tools to create an interface designed to implement ethical frameworks with AI.',
    linkedInUrl: 'https://www.linkedin.com/in/dylan-cathapermal/',
    gitHubUrl: 'https://github.com/dcathapermal',
  },
  {
    name: 'Lorenzo Canonico',
    title: 'Alumni, PhD',
    program: 'Human Centered Computing',
    img_cat: 'alumni',
    researchInterests: ['Artificial Intelligence','Game Theory','Philosophy','Film'],
    description: 'Lorenzo is a graduate student in the Human-Centered Computing program at Clemson University.  He lead a start-up company that developed financial analysis software that assesses and compares financial performance.  He is passionate about providing pro-bono application development for non-profit organizations.',
    personalWebsiteUrl: 'https://lbarberiscanoni.github.io/',
    linkedInUrl: 'https://www.linkedin.com/in/lorenzo-barberis-canonico-612734aa',
    googleScholarUrl: 'https://scholar.google.com/scholar?hl=en&as_sdt=0%2C41&q=Lorenzo+Barberis+Canonico&btnG=',
    gitHubUrl: 'https://github.com/lbarberiscanoni',
  },
  {
    name: 'Rohit Mallick',
    title: 'PhD Student',
    img_cat: 'current',
    program: 'Computer Science',
    researchInterests: ["Human-AI Teaming", "Human-Centered AI", "Affective Computing"],
    description: "Hiya! My name is Rohit Mallick, and I'm from Bel Air, Maryland. My family has always been interested in exploring new places and that's why I'm no different! I've visited Western Europe, India, Nepal, Singapore, Thailand and more! When choosing an undergraduate college, I knew I needed to leave Maryland, so I ventured off and became a Purdue University Boilermaker. In May 2020, I successfully graduated with a bachelor's degree in brain and behavioral sciences with a minor in computer science. My experiences at Purdue and my summer internships at the U.S. Army Research Lab led me to Clemson's TRACE Lab to pursue research as a career. I am pursuing a Human-Centered Computing Ph.D. and focusing on designing effective AI teammates that motivate and inspire their human teammates within human-AI teams. I am eager to continue making a positive difference within the field of human-computer interaction and look forward to learning more about you! Thanks for visiting!",
    linkedInUrl: 'www.linkedin.com/in/rohit-mallick-phd',
    googleScholarUrl: "https://scholar.google.com/citations?user=HIo7kwwAAAAJ&hl=en",
    personalWebsiteUrl:"rohitmallick.com"
  },
  {
    name: 'Richard Garcia',
    title: 'Undergraduate Student, Alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    description: 'Hello everyone, my name is Richard Garcia and I am from Greenville, South Carolina. I am first-generation American as well as college student and happy that I can call also myself a first-generation Clemson Tiger. I am an undergraduate majoring in Computer Science with minor in Business Administration. I have always been intrigued the impact of technological advancements in society, especially in hospitals and public health and will be getting my master’s in biomedical data and Informatics at Clemson. TRACE Lab and Bart Swecker and Nathan McNeese’s Analytics and Data Lab has allowed me to explore just that through the research I conduct through them. I am currently working on an investigation on the perspectives of college students and their individual location privacy and institutional trust when adopting a campus-wide digitized contact tracing solution in the COVID-19 era.',
    linkedInUrl: 'https://www.linkedin.com/in/richard-garcia2000',
  },
  {
    name: 'Jada Houser',
    title: 'Undergraduate Student, Alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    description: "Hiya! My name is Jada Houser. I’m a fifth year undergraduate student at Clemson University currently pursuing a Bachelor's degree in Computer Science and minors in Economics and Mandarin Chinese. As an undergraduate researcher, I’m interested in exploring ways in which automation can be applied to the economic research process and generally speaking, ways in which computer science and economics can be more interdisciplinary. Additionally, I have interests in financial stability, monetary policy, data science, automation, bots, and AI generally. On the less technical side, I enjoy designing graphics, websites, drawing on my phone, and playing video games. I also love cooking and baking food from different cuisines (esp. Chinese) and participating in hackathons with my friends.",
    personalWebsiteUrl: 'https://www.jadahouser.info/',
    linkedInUrl: 'https://www.linkedin.com/in/jada-a-houser-6903a6164/',
  },
  {
    name: 'Thomas Lee',
    title: 'Undergraduate Student, Alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    description: 'Hello! My name is Thomas “Top” Lee and I am a senior computer science student with a minor in philosophy. I am here at Clemson all the way from the island of Bermuda out in the Atlantic and I am incredibly happy to study at this university. There are few places, in my biased opinion, just as beautiful as Bermuda and Clemson is definitely on that list. The TRACE lab is exactly what I was looking for in a research lab due to their strong consideration of ethical problems, as well as the exciting work they do with artificial intelligence. I am excited to be doing full stack development for a project on how AI and humans interact with each other when faced with ethical dilemmas.',
    linkedInUrl: 'https://www.linkedin.com/in/topflee',
  },
  {
    name: 'Houston Everett',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'Ahoy! I’m Houston. I’m a senior CS student at Clemson and a big fan of coding.',
  },
  {
    name: 'Joshua Little',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'My name is Joshua Little, I am from Lexington, SC and am currently a sophomore at Clemson University majoring in computer science. I am passionate about computer programming and designing software. In my free time I like talking about philosophy and politics, playing video games, and hanging out with friends.',
    personalWebsiteUrl: 'https://jlittle.dev/',
    linkedInUrl: 'https://www.linkedin.com/in/mjtlittle/',
    gitHubUrl: 'https://github.com/Mjtlittle',
  },
  {
    name: 'Alyssa Williams',
    title: 'Undergraduate Student, Alumni',
    program: 'Computer Science',
    img_cat: 'alumni',
    description: 'Hi, my name’s Alyssa! I’m a sophomore in Computer Science at Clemson and I’m interested in programming and teaching what I know!',
    linkedInUrl: 'http://www.linkedin.com/in/alyssa-williams-3828b7202',
    gitHubUrl: 'https://github.com/LisLis294',
  },
  {
    name: 'Allyson Hauptman',
    title: 'PhD Student, Alumni',
    img_cat: 'alumni',
    program: 'Human Centered Computing',
    researchInterests: ['Cyber Defense Policy','Human-AI Teaming in Cyber Incident Response'],
    description: 'CPT Allyson Hauptman graduated the United States Military Academy in 2014 with a double major in Information Technology Systems and International Legal Studies. She traveled to Estonia on a Rotary Scholarship and earned her Master’s in Cyber Security with a specializationin Digital Forensics from Tallinn University of Technology. Her master’s thesis was the design, implementation and assessment of the first digital forensics challenge in the Locked Shields NATO Cyber Defense Exercise, an international cyber security exercise held annually by the NATO Cooperative Cyber Center of Excellence. Following graduation, she moved to Augusta, Georgia, where she currently serves as a Cyber Operations Officer in the US Army. Her military experience includes time as a Mission Element Lead on a Cyber Protection Team and as a Company Commander in the Army’s Cyber Warfare Battalion. Her research interests include cyber defense policy and human-AI teaming in cyber incident response. ',
  },
  {
    name: 'Caitlin Lancaster',
    title: 'PhD Student, Alumni',
    img_cat: 'alumni',
    program: 'Human Centered Computing',
    description: 'Hello! My name is Caitlin Lancaster and I’m originally from Plymouth, MN. Currently, I am working toward my Ph.D. in Human Centered Computing. Before joining the program, I received my M.A. in Communication, Technology, and Society from Clemson, during which I taught public speaking and introduction to communication courses. Outside of academia, I have professional experience in social media and digital marketing, public relations, and digital media production.',
    linkedInUrl: 'https://www.linkedin.com/in/caitlinlancaster/',
  },
  {
    name: 'Jake Macdonald',
    title: 'Undergraduate Student, Alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    description: 'As the large bold suggests, I am Jake. I LOVE creative problem solving, and computer science offers me an effective medium. After graduating in 2024, academia will yet escape me, I am pursuing an advanced degree in some facet of applied artificial intelligence. I also am the developer of this swanky webpage!',
    linkedInUrl: 'https://www.linkedin.com/in/jake-macdonald-2b060020b/',
    gitHubUrl: 'https://github.com/JakeMacdona1d',
  },
  {
    name: 'Christian Ihekweazu',
    title: 'Undergraduate Student',
    img_cat: 'current',
    program: 'Computer Science',
    description: 'Hi, my name is Christian! I am a freshman majoring in computer science. My favorite hobbies include working out, playing video games, programming, and learning new things! After graduating, I plan on pursuing an advanced degree in the computer science field. My dream job would be to become either a software engineer or a machine learning engineer.',
    linkedInUrl: 'https://www.linkedin.com/in/christian-ihekweazu-307547206',
  },
  {
    name: 'Noah Tavarez',
    title: 'Undergraduate Student, Alumni',
    img_cat: 'alumni',
    program: 'Computer Science',
    description: `Hey, my name is Noah Tavarez and I'm a sophomore Honors student majoring in Computer Science. I've developed a great interest in Web 3.0, cryptocurrency, and the programming behind them. I'm always looking for new challenges and ways to broaden my horizons!`,
    linkedInUrl: 'https://www.linkedin.com/in/noah-tavarez-099239236',
  },
  {
    name: 'Wen Duan',
    title: 'Poct-Doctorate Researcher',
    img_cat: 'alumni',
    program: 'Postdoc',
    description: `My name is Wen Duan, a postdoc at TRACE. I received my PhD in communication and human-computer interaction from Cornell University. My work looks at how technology (especially various forms of AI, conversation agent) can be leveraged to facilitate communication across linguistic and cultural (and various other) boundaries, to induce desired social processes to enhance teamwork, etc. Outside of work I like all sorts of cool sports including figure skating and skateboarding.`,
    linkedInUrl: 'https://www.linkedin.com/in/wen-emily-duan-90706312b/',
  },
  {
    name: "Kyle Zheng",
    title: "Undergraduate Student",
    img_cat: "current",
    program: 'Computer Science',
    description: "Hi, my name is Kyle, and I’m from Myrtle Beach, South Carolina! I am a sophomore majoring in computer science. My current interests are in artificial intelligence, machine learning, and more recently, robotics (Ghost & Spot). During my free time, I enjoy working out and watching my favorite team, the Pistons, play. I’m looking forward to capitalizing on my time with TRACE.",
    linkedInUrl: "Linkedin- https://www.linkedin.com/in/kyle-zheng2/"
  },
  {
    name: "Swapnil Srivastava",
    title: "Masters Student, Alumni",
    img_cat: "alumni",
    program: 'Computer Science',
    description: "I am an AI Research Assistant at Clemson University’s TRACE Human-AI Laboratory. In the final semester of Masters in Computer Science.",
    linkedInUrl: "https://www.linkedin.com/in/swapnil-srivastava-00aba0148",
    personalWebsiteUrl: 'swapnilsrivastava3051.com',
    gitHubUrl: 'https://github.com/cflathm',
  },
  {
    name: "Ethan Johnson",
    title: "Undergraduate Student, Alumni",
    img_cat: 'alumni',
    program: 'Computer Science',
    description: "Hi! I'm Ethan Johnson! I'm a senior Computer Science major with a minor in Psychology graduating in spring 2024! I have lots of interests and hobbies but some of my current favorites are rock climbing, orienteering, running, reading, poetry, and sudoku.",
    linkedInUrl:"https://www.linkedin.com/in/ethanvjohnson/ https://github.com/ethanvjohnson"
  },
  {
    name: "Nan(Phoebe) Weng",
    title: "PhD Student",
    img_cat: "current",
    program: "Computer Science",
    researchInterests: ["Human-AI Teaming", "User Experience in AI", "Human-AI Collaboration"],
    description: "Hello! I'm Nan, also known as Phoebe. I'm currently pursuing a Ph.D. with a focus on human-AI teaming and collaboration, particularly within industry-based human-AI teams. My research is centered on enhancing the user experience in these collaborative environments. I hold an M.A. in Media and Information, specializing in Human-Computer Interaction (HCI) and User Experience (UX) from Michigan State University. Before diving into my Ph.D. journey, I’ve worked in various industries and gained diverse experience in news media, social media, education consulting, and big tech companies. Outside of work, I’m a big fan of swimming and enjoy practicing yoga and Pilates.",
    linkedInUrl: "https://www.linkedin.com/in/nan-phoebe-weng-89b5801a0"
  },
  {
    name: "Yunhao Wang",
    title: "PhD Student",
    img_cat: "current",
    program: "Computer Science",
    description: "Hi, I am Yunhao Wang from Shanghai, China. I received my Bachelor of Science in Computer Science from the University of Michigan in 2021, followed by a Master of Science in Computer Science and Engineering from the same university. I started my PhD in Human-Centered Computing in 2024 under the supervision of Dr. Nathan McNeese and joined Trace Research Group. My interest in human-centered computing is driven by the belief that the synergy between humans and machines can unleash unprecedented levels of energy and creativity in society." ,
  },
  {
    name: "Mia Yancey",
    title: "Undergraduate Student",
    img_cat: "current",
    program: "Computer Science",
    description: "Hi! I'm Mia and I'm an undergraduate sophomore computer science major with a minor in history. I was raised in Myrtle Beach, SC with my parents and two sisters, and my twin cats, Klaus and Vanya. I love data science and exploring the intersection between history and technology, and I look forward to learning how technology can be used to help humans do their jobs more efficiently! When I finish my undergraduate degree I hope to go on to graduate school, and my dream job would be to one day work in museums or the national archives helping to make long dormant historical records accessible to the public.",
    linkedInUrl: "www.linkedin.com/in/mia-yancey"
  },
  // {
  //   name: ,
  //   title: ,
  //   img_cat: ,
  //   program: ,
  //   description: ,
  //   linkedInUrl:
  // },
  // {
  //   name: ,
  //   title: ,
  //   img_cat: ,
  //   program: ,
  //   description: ,
  //   linkedInUrl:
  // },
  // {
  //   name: ,
  //   title: ,
  //   img_cat: ,
  //   program: ,
  //   description: ,
  //   linkedInUrl:
  // },
];
